### ISSUE TITLE
Regression in TLS

### ISSUE THREAD

**Issue by pcapdump** [zaleos/sipplauncher#51]
**Description**

TLS tests fail with exception:

```
sipplauncher 0.0.13-beta ERROR 2020-02-12-19:17:37 Caught exception while running test: can't pickle _cffi_backend.CDataGCP objects
sipplauncher 0.0.13-beta DEBUG 2020-02-12-19:17:37 can't pickle _cffi_backend.CDataGCP objects
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sipplauncher-0.0.13b0-py3.6.egg/sipplauncher/Test.py", line 370, in run
    self.__do_run(run_id_prefix, args)
  File "/usr/local/lib/python3.6/site-packages/sipplauncher-0.0.13b0-py3.6.egg/sipplauncher/Test.py", line 352, in __do_run
    p.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_forkserver.py", line 47, in _launch
    reduction.dump(process_obj, buf)
  File "/usr/lib64/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle _cffi_backend.CDataGCP objects
```

**Acceptance criteria**

TLS should be working without exceptions.

**Comment by pcapdump** [comment]
Likely it's caused by https://github.com/zaleos/sipplauncher/issues/45
